// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package account

import (
	"database/sql"
	"github.com/ricardominze/gobootstrap/core/domain/account/service"
	"github.com/ricardominze/gobootstrap/infra/adapter"
)

// Injectors from account_di.go:

func NewAccountDependenciesInjection(db *sql.DB) *account_service.AccountService {
	accountRepository := adapter.NewAccountRepository(db)
	accountService := account_service.NewAccountService(accountRepository)
	return accountService
}
