services:
  app:
    image: golang:1.23
    container_name: bank-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["go", "run", "./main.go"]
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_db:/var/lib/mysql      
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    restart: always
volumes:
  mysql_db:
