services:
  app:
    image: golang:1.23
    container_name: bank-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["go", "run", "./main.go"]
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
volumes:
  postgres_data:
