-- +goose Up
-- +goose StatementBegin
CREATE TABLE account (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_customer INTEGER NOT NULL,
    type_account VARCHAR(50) NOT NULL,
    balance DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    status INTEGER DEFAULT 1 NOT NULL,
    CONSTRAINT fk_account_customer FOREIGN KEY (id_customer) REFERENCES customer(id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE account;
-- +goose StatementEnd
